import '../../globals.css'
import type { Metadata } from 'next'
import Page from '@/components/Page'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

import { ThemeProvider } from "@/components/theme-provider"
import { loadPost } from '../loadPost'


export const metadata: Metadata = {
  title: 'Create Next App!!',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, ...args }: { children: React.ReactNode }) {
  const slug = children?.props?.childProp.segment
  const post = await loadPost(slug);
  console.log(Object.keys(post))
  metadata.title = post.slug
  metadata.description = post?.excerpt
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Page>
          <h1 className={`text-3xl md:text-5xl capitalize mb-2 font-bold -tracking-tighter mb-6`}>
          hia
        </h1>
            {children}
          </Page>
        </ThemeProvider>
      </body>
    </html>
  )
}
